// Meta simulator: plays every archetype against every other with the real
// rules engine (game.js) and the same squad AI the in-game rival uses
// (ai.js) on both sides, then writes src/metaData.js with the win-rate
// matrix, tiers, who-beats-whom and counter-meta picks the team screen
// shows. Each pairing is played half the games from each side of the
// board so neither archetype profits from the arena's asymmetry.
//
//   npm run meta            # default number of games per pairing
//   node scripts/simulate-meta.mjs 400
import { writeFileSync } from 'node:fs';
import * as game from '../src/game.js';
import { aiBeginCard, aiMoveIntent } from '../src/ai.js';
import { ARCHETYPES, copyArchetypePicks } from '../src/cards.js';

// Seeded RNG so `npm run meta` always writes the same numbers for the
// same rules (card picks and AI timing all go through Math.random).
let seed = 20260924;
Math.random = () => {
  seed |= 0; seed = seed + 0x6D2B79F5 | 0;
  let t = Math.imul(seed ^ seed >>> 15, 1 | seed);
  t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
  return ((t ^ t >>> 14) >>> 0) / 4294967296;
};

const GAMES_PER_PAIR = Number(process.argv[2]) || 400;
const DT = 0.1;
const MAX_TIME = 300;
const AI_SPEED = 1.3; // same as the in-game rival
const BEATS_AT = 0.55; // a matchup won this often counts as favored / a counter

const CAST = { you: 'castYou', rival: 'castRival' };
let duels = 0, duelSeconds = 0, timeouts = 0;

// Returns 1 if `you` wins, 0 if `rival` wins, 0.5 for a draw/timeout.
function playDuel(youPicks, rivalPicks){
  const st = game.freshState(youPicks, rivalPicks);
  const pending = [];
  const think = { you: 2.5, rival: 2.5 };
  const move = { you: null, rival: null };
  const moveTimer = { you: 0, rival: 0 };
  let t = 0;
  while (!st.gameOver && t < MAX_TIME){
    t += DT;
    game.tickEnergyRealtime(st, DT);
    game.tickCasts(st, DT);
    game.tickStatusTimer(st, DT);
    for (const side of ['you', 'rival']){
      moveTimer[side] -= DT;
      if (moveTimer[side] <= 0){
        move[side] = aiMoveIntent(st, side);
        moveTimer[side] = 0.5;
      }
      if (move[side]) game.moveSquadWithTank(st, side, move[side].x * AI_SPEED * DT, move[side].z * AI_SPEED * DT);
      if (st[CAST[side]] <= 0){
        think[side] -= DT;
        if (think[side] <= 0){
          think[side] = 0.6 + Math.random() * 1.2;
          const plan = aiBeginCard(st, side);
          if (plan) pending.push({ plan, at: t + game.CAST_IMPACT_AT });
        }
      }
    }
    for (let i = pending.length - 1; i >= 0; i--){
      if (t >= pending[i].at){
        game.landCast(st, pending[i].plan);
        pending.splice(i, 1);
      }
    }
    game.checkGameOver(st);
  }
  duelSeconds += t;
  duels++;
  if (!st.gameOver){ timeouts++; return 0.5; }
  return st.winner === 'you' ? 1 : st.winner === 'rival' ? 0 : 0.5;
}

const ids = ARCHETYPES.map(a => a.id);
const matrix = Object.fromEntries(ids.map(id => [id, {}]));
const started = Date.now();
for (let i = 0; i < ARCHETYPES.length; i++){
  for (let j = i + 1; j < ARCHETYPES.length; j++){
    const A = ARCHETYPES[i], B = ARCHETYPES[j];
    let aScore = 0;
    for (let g = 0; g < GAMES_PER_PAIR; g++){
      aScore += g % 2 === 0
        ? playDuel(copyArchetypePicks(A), copyArchetypePicks(B))
        : 1 - playDuel(copyArchetypePicks(B), copyArchetypePicks(A));
    }
    const rate = aScore / GAMES_PER_PAIR;
    matrix[A.id][B.id] = Math.round(rate * 1000) / 1000;
    matrix[B.id][A.id] = Math.round((1 - rate) * 1000) / 1000;
  }
  process.stdout.write(`${ARCHETYPES[i].id} done (${((Date.now() - started) / 1000).toFixed(1)}s)\n`);
}

const winRate = Object.fromEntries(ids.map(id => {
  const rates = ids.filter(o => o !== id).map(o => matrix[id][o]);
  return [id, Math.round(rates.reduce((a, r) => a + r, 0) / rates.length * 1000) / 1000];
}));

// Rank-based tiers so there is always a clear meta: top 2 = S (meta),
// next 3 = A, next 3 = B, rest = C.
const ranked = [...ids].sort((a, b) => winRate[b] - winRate[a]);
const tier = {};
ranked.forEach((id, i) => { tier[id] = i < 2 ? 'S' : i < 5 ? 'A' : i < 8 ? 'B' : 'C'; });

const beats = {}, counteredBy = {}, counterMetaVs = {};
ids.forEach(id => {
  beats[id] = ids.filter(o => o !== id && matrix[id][o] >= BEATS_AT).sort((a, b) => matrix[id][b] - matrix[id][a]);
  counteredBy[id] = ids.filter(o => o !== id && matrix[o][id] >= BEATS_AT).sort((a, b) => matrix[b][id] - matrix[a][id]);
  counterMetaVs[id] = tier[id] === 'S' ? [] : beats[id].filter(o => tier[o] === 'S');
});

const avgDuelSeconds = Math.round(duelSeconds / duels);
const META = { gamesPerPair: GAMES_PER_PAIR, beatsAt: BEATS_AT, avgDuelSeconds, timeoutShare: Math.round(timeouts / duels * 1000) / 1000, ranked, winRate, tier, beats, counteredBy, counterMetaVs, matrix };
writeFileSync(new URL('../src/metaData.js', import.meta.url),
  `// Generated by scripts/simulate-meta.mjs (npm run meta) -- do not edit by hand.\n` +
  `// AI-vs-AI duels with the real rules; see README "Meta e contra-meta".\n` +
  `export const META = ${JSON.stringify(META, null, 2)};\n`);

console.log(`\n${duels} duels, avg ${avgDuelSeconds}s, ${(timeouts / duels * 100).toFixed(1)}% hit the ${MAX_TIME}s cap`);
console.log('rank  tier  win%   archetype        beats / countered by');
ranked.forEach((id, i) => console.log(
  `${String(i + 1).padStart(3)}   ${tier[id]}    ${(winRate[id] * 100).toFixed(1).padStart(5)}  ${id.padEnd(16)} +[${beats[id].join(',')}]  -[${counteredBy[id].join(',')}]` +
  (counterMetaVs[id].length ? `  COUNTER-META vs ${counterMetaVs[id].join(',')}` : '')));
