// Generated by scripts/simulate-meta.mjs (npm run meta) -- do not edit by hand.
// AI-vs-AI duels with the real rules; see README "Meta e contra-meta".
export const META = {
  "gamesPerPair": 400,
  "beatsAt": 0.55,
  "avgDuelSeconds": 154,
  "timeoutShare": 0,
  "ranked": [
    "heal",
    "hybrid",
    "bleed",
    "mirage",
    "damage",
    "thorns",
    "bastion",
    "toxic",
    "deathmark",
    "poison"
  ],
  "winRate": {
    "bleed": 0.543,
    "poison": 0.409,
    "damage": 0.532,
    "heal": 0.566,
    "thorns": 0.489,
    "mirage": 0.541,
    "bastion": 0.468,
    "deathmark": 0.446,
    "toxic": 0.463,
    "hybrid": 0.545
  },
  "tier": {
    "heal": "S",
    "hybrid": "S",
    "bleed": "A",
    "mirage": "A",
    "damage": "A",
    "thorns": "B",
    "bastion": "B",
    "toxic": "B",
    "deathmark": "C",
    "poison": "C"
  },
  "beats": {
    "bleed": [
      "thorns",
      "deathmark",
      "heal"
    ],
    "poison": [],
    "damage": [
      "bastion",
      "poison",
      "bleed",
      "toxic"
    ],
    "heal": [
      "deathmark",
      "poison",
      "toxic",
      "bastion"
    ],
    "thorns": [],
    "mirage": [
      "poison",
      "toxic",
      "damage",
      "deathmark",
      "heal",
      "bastion"
    ],
    "bastion": [
      "deathmark"
    ],
    "deathmark": [
      "poison"
    ],
    "toxic": [
      "poison"
    ],
    "hybrid": [
      "bastion",
      "toxic",
      "heal",
      "poison",
      "mirage"
    ]
  },
  "counteredBy": {
    "bleed": [
      "damage"
    ],
    "poison": [
      "heal",
      "toxic",
      "mirage",
      "damage",
      "hybrid",
      "deathmark"
    ],
    "damage": [
      "mirage"
    ],
    "heal": [
      "hybrid",
      "mirage",
      "bleed"
    ],
    "thorns": [
      "bleed"
    ],
    "mirage": [
      "hybrid"
    ],
    "bastion": [
      "hybrid",
      "heal",
      "damage",
      "mirage"
    ],
    "deathmark": [
      "heal",
      "bastion",
      "bleed",
      "mirage"
    ],
    "toxic": [
      "heal",
      "hybrid",
      "mirage",
      "damage"
    ],
    "hybrid": []
  },
  "counterMetaVs": {
    "bleed": [
      "heal"
    ],
    "poison": [],
    "damage": [],
    "heal": [],
    "thorns": [],
    "mirage": [
      "heal"
    ],
    "bastion": [],
    "deathmark": [],
    "toxic": [],
    "hybrid": []
  },
  "matrix": {
    "bleed": {
      "poison": 0.526,
      "damage": 0.43,
      "heal": 0.558,
      "thorns": 0.648,
      "mirage": 0.546,
      "bastion": 0.475,
      "deathmark": 0.639,
      "toxic": 0.521,
      "hybrid": 0.544
    },
    "poison": {
      "bleed": 0.474,
      "damage": 0.403,
      "heal": 0.233,
      "thorns": 0.518,
      "mirage": 0.359,
      "bastion": 0.47,
      "deathmark": 0.441,
      "toxic": 0.35,
      "hybrid": 0.435
    },
    "damage": {
      "bleed": 0.57,
      "poison": 0.597,
      "heal": 0.533,
      "thorns": 0.513,
      "mirage": 0.428,
      "bastion": 0.598,
      "deathmark": 0.458,
      "toxic": 0.558,
      "hybrid": 0.533
    },
    "heal": {
      "bleed": 0.443,
      "poison": 0.768,
      "damage": 0.468,
      "thorns": 0.464,
      "mirage": 0.435,
      "bastion": 0.63,
      "deathmark": 0.779,
      "toxic": 0.684,
      "hybrid": 0.423
    },
    "thorns": {
      "bleed": 0.353,
      "poison": 0.483,
      "damage": 0.488,
      "heal": 0.536,
      "mirage": 0.509,
      "bastion": 0.518,
      "deathmark": 0.466,
      "toxic": 0.496,
      "hybrid": 0.549
    },
    "mirage": {
      "bleed": 0.454,
      "poison": 0.641,
      "damage": 0.573,
      "heal": 0.565,
      "thorns": 0.491,
      "bastion": 0.554,
      "deathmark": 0.566,
      "toxic": 0.588,
      "hybrid": 0.436
    },
    "bastion": {
      "bleed": 0.525,
      "poison": 0.53,
      "damage": 0.402,
      "heal": 0.37,
      "thorns": 0.483,
      "mirage": 0.446,
      "deathmark": 0.643,
      "toxic": 0.498,
      "hybrid": 0.313
    },
    "deathmark": {
      "bleed": 0.361,
      "poison": 0.559,
      "damage": 0.543,
      "heal": 0.221,
      "thorns": 0.534,
      "mirage": 0.434,
      "bastion": 0.358,
      "toxic": 0.525,
      "hybrid": 0.478
    },
    "toxic": {
      "bleed": 0.479,
      "poison": 0.65,
      "damage": 0.443,
      "heal": 0.316,
      "thorns": 0.504,
      "mirage": 0.413,
      "bastion": 0.502,
      "deathmark": 0.475,
      "hybrid": 0.388
    },
    "hybrid": {
      "bleed": 0.456,
      "poison": 0.565,
      "damage": 0.468,
      "heal": 0.578,
      "thorns": 0.451,
      "mirage": 0.564,
      "bastion": 0.688,
      "deathmark": 0.523,
      "toxic": 0.613
    }
  }
};
